### ISSUE TITLE
"TypeError: isinstance() arg 2 must be a type or tuple of types" error

### ISSUE THREAD

**Issue by Rothax** [AdamSpannbauer/python_video_stab#119]
I am trying to run this code in a raspberry 4.b. But it gives this error
![error](https://user-images.githubusercontent.com/54594660/106313882-fb343680-6279-11eb-9c15-d38044e02ea9.PNG)

pi@raspberrypi:~/python_video_stab-master/vidstab $ python3 videocap.py
Traceback (most recent call last):
  File "videocap.py", line 6, in <module>
    max_frames=1000
  File "/home/pi/.local/lib/python3.7/site-packages/vidstab/VidStab.py", line 551, in stabilize
    self.frame_queue.set_frame_source(cv2.VideoCapture(input_path))
  File "/home/pi/.local/lib/python3.7/site-packages/vidstab/frame_queue.py", line 36, in set_frame_source
    if isinstance(source, cv2.VideoCapture):
TypeError: isinstance() arg 2 must be a type or tuple of types

**Comment by yzn9961** [comment]
Hey,Rothax. I just solved this problem by changing the two `isinstance()`functions in  `/home/pi/.local/lib/python3.7/site-packages/vidstab/frame_queue.py` from
```python
isinstance(source, cv2.VideoCapture):
```
to 
 ```python 
   isinstance(source, type(cv2.VideoCapture())):
```
Then it works. Hope that helps you.

**Comment by AdamSpannbauer** [comment]
Sorry for the lack of any development on this project.  I didn't even see this issue was opened until @yzn9961's comment.

I'll implement the change shown above.  Thanks for the solve.
