### ISSUE TITLE
Re-visit autoborder

### ISSUE THREAD

**Issue by AdamSpannbauer** [AdamSpannbauer/python_video_stab#87]
Verify autoborder feature is working as expected

**Comment by hopperelec** [comment]
It doesn't seem to be for me
```
Traceback (most recent call last):
  File "...\main.py", line 90, in <module>
    compress_video(videos[0])
  File "...\main.py", line 46, in compress_video
    frame = stabilizer.stabilize_frame(input_frame=frame, smoothing_window=SMOOTHING_WINDOW, border_size='auto')
  File "...\venv\lib\site-packages\vidstab\VidStab.py", line 468, in stabilize_frame
    self._set_border_options(border_size, border_type)
  File "...\venv\lib\site-packages\vidstab\VidStab.py", line 248, in _set_border_options
    functional_border_size, functional_neg_border_size = border_utils.functional_border_sizes(border_size)
  File "...\venv\lib\site-packages\vidstab\border_utils.py", line 19, in functional_border_sizes
    if border_size < 0:
TypeError: '<' not supported between instances of 'str' and 'int'
```
