### ISSUE TITLE
vidstab installation

### ISSUE THREAD

**Issue by rijutawankar** [AdamSpannbauer/python_video_stab#9]
Every time i try to run this command, I get this error, can you help me understand what I am doing wrong

```bash
(videostab) rijuta@rijuta-HP-Notebook:~/PycharmProjects/python_video_stab-master$ python3 -m vidstab -i input_ostrich.gif -o stable_video1.avi -k GFTT
Progress bar is based on cv2.CAP_PROP_FRAME_COUNT which may be inaccurate

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rijuta/PycharmProjects/python_video_stab-master/vidstab/__main__.py", line 32, in <module>
    stabilizer.stabilize(input_path=args['input'], output_path=args['output'])
  File "/home/rijuta/PycharmProjects/python_video_stab-master/vidstab/VidStab.py", line 310, in stabilize
    show_progress=True)
  File "/home/rijuta/PycharmProjects/python_video_stab-master/vidstab/VidStab.py", line 174, in gen_transforms
    self.transforms = np.array(self._raw_transforms + (self.smoothed_trajectory - self.trajectory))
  File "/home/rijuta/.virtualenvs/videostab/lib/python3.5/site-packages/pandas/core/generic.py", line 1607, in __array_wrap__
    return self._constructor(result, **d).__finalize__(self)
  File "/home/rijuta/.virtualenvs/videostab/lib/python3.5/site-packages/pandas/core/frame.py", line 379, in __init__
    copy=copy)
  File "/home/rijuta/.virtualenvs/videostab/lib/python3.5/site-packages/pandas/core/frame.py", line 536, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "/home/rijuta/.virtualenvs/videostab/lib/python3.5/site-packages/pandas/core/internals.py", line 4859, in create_block_manager_from_blocks
    mgr = BlockManager(blocks, axes)
  File "/home/rijuta/.virtualenvs/videostab/lib/python3.5/site-packages/pandas/core/internals.py", line 3282, in __init__
    self._verify_integrity()
  File "/home/rijuta/.virtualenvs/videostab/lib/python3.5/site-packages/pandas/core/internals.py", line 3498, in _verify_integrity
    len(self.items), tot_items))
AssertionError: Number of manager items must equal union of block items
# manager items: 1, # tot_items: 0
```

**Comment by AdamSpannbauer** [comment]
This error is due to the input being a `.gif`.   It should work if you provide a typical video file as input (i.e. `.mp4`, `.avi`, etc).  

If you want to recreate the ostrich results from the documentation you can [find the input video here](https://s3.amazonaws.com/python-vidstab/ostrich.mp4).  You can download the video or try and use the URL directly as the input (see below).  Using the URL directly has a chance to fail depending on your setup, but downloading first should allow you to get results.

```bash
python3 -m vidstab -i https://s3.amazonaws.com/python-vidstab/ostrich.mp4 -o stable_video1.avi
```

**Comment by AdamSpannbauer** [comment]
I just pushed an update to the master branch that should fix the issue of using gifs as input.  I don't plan on re-publishing to pypi just yet, but you should be able to pip install from github (see below) and then process gifs.

Please report back if you have any issues.  If not I will close this issue.  Thanks for reporting!

**Comment by rijutawankar** [comment]
Thank you Adam for replying. it worked with ,mp4 file. will try using gif as you updated. Thanks again for making out time to reply.
